# Profil Développement
spring:
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true

  flyway:
    clean-disabled: false

logging:
  level:
    com.example.app: DEBUG
    org.springframework.security: INFO
    org.flywaydb: INFO

